# Generated by Django 5.1.4 on 2025-01-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptmodel',
            name='bonus_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='receiptmodel',
            name='custom_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='receiptmodel',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
