# Generated by Django 5.1.4 on 2024-12-29 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('return_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tip_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True, help_text='Check this box if the service is completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.receiptmodel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.staff')),
            ],
            options={
                'verbose_name': 'Staff Receipt',
                'verbose_name_plural': 'Staff Receipts',
                'ordering': ['-created_at'],
            },
        ),
    ]
