# Generated by Django 5.1.4 on 2025-01-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_receiptmodel_bonus_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='commission_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
