# Generated by Django 5.1.4 on 2025-02-05 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_salonservicecategorymodel_alter_staff_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonservicecategorymodel',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='salon.salon'),
        ),
        migrations.AddField(
            model_name='salonservicemodel',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='salon.salon'),
        ),
    ]
