# Generated by Django 5.1.4 on 2024-12-29 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_alter_receiptmodel_return_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreceipt',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_receipts', to='salon.receiptmodel'),
        ),
    ]
