# Generated by Django 5.1.4 on 2025-02-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_salonservicecategorymodel_salon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonservicemodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check this box if the service is active'),
        ),
    ]
