# Generated by Django 5.1.4 on 2025-02-06 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_salonservicemodel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salon.salonservicemodel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salon.staff')),
            ],
            options={
                'verbose_name': 'Staff Skill',
                'verbose_name_plural': 'Staff Skills',
                'ordering': ['-created_at'],
            },
        ),
    ]
