# Generated by Django 5.1.4 on 2025-01-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_alter_staffreceipt_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffreceipt',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='staffreceipt',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
