# Generated by Django 5.1.4 on 2025-02-06 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_staffskillmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffskillmodel',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='salon.staff'),
        ),
    ]
