# Generated by Django 5.1.4 on 2025-01-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_staffreceipt_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreceipt',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
