# Generated by Django 5.1.4 on 2025-01-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_alter_staffreceipt_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreceipt',
            name='discount_percent',
            field=models.FloatField(default=0),
        ),
    ]
