# Generated by Django 5.1.4 on 2025-02-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_alter_staffskillmodel_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffskillmodel',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='staffskillmodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check this box if the skill is active'),
        ),
    ]
