# Generated by Django 5.1.4 on 2025-02-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_staffskillmodel_custom_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffskillmodel',
            name='custom_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffskillmodel',
            name='custom_duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
