# Generated by Django 5.1.4 on 2025-01-04 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptmodel',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salon.salon'),
        ),
        migrations.AddField(
            model_name='staff',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salon.salon'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
