# Generated by Django 5.1.4 on 2025-02-07 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_staffskillmodel_custom_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTurnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(blank=True, max_length=50, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('custom_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('custom_description', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('tip_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_turns', to='salon.receiptmodel')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_turns', to='salon.salon')),
                ('services', models.ManyToManyField(related_name='staff_turns', to='salon.salonservicemodel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_turns', to='salon.staff')),
            ],
            options={
                'verbose_name': 'Staff Turn',
                'verbose_name_plural': 'Staff Turns',
                'ordering': ['-created_at'],
            },
        ),
    ]
