# Generated by Django 5.1.4 on 2025-02-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_staffturnmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffturnmodel',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
