# Generated by Django 5.1.4 on 2025-02-17 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_staffturnmodel_finished_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_percentage', models.FloatField(blank=True, default=0, null=True)),
                ('passcode', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='salon_logo/')),
                ('background_color', models.CharField(blank=True, max_length=100, null=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salon.salon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
