# Generated by Django 5.1.4 on 2025-01-08 03:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0011_alter_receiptmodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreceipt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='staffreceipt',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
