# Generated by Django 5.1.4 on 2025-02-17 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0011_salonsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonsetting',
            name='salon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='salon_setting', to='salon.salon'),
        ),
    ]
