# Generated by Django 5.1.4 on 2025-02-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0012_alter_salonsetting_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonsetting',
            name='logo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
