# Generated by Django 5.1.4 on 2025-02-18 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0013_salonsetting_logo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salonsetting',
            old_name='tax_percentage',
            new_name='tax_rate',
        ),
    ]
